name: Deploy
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 * * * *'
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        run: wget https://github.com/gohugoio/hugo/releases/download/v0.81.0/hugo_extended_0.81.0_Linux-64bit.deb -O /tmp/hugo.deb && sudo dpkg -i /tmp/hugo.deb

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: |
          cd public && \
          git init && \
          git config user.name "GitHub Actions" && \
          git config user.email noreply@github.com && \
          git remote add origin https://percona:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git && \
          git add . && \
          git commit -m "Website publish" && \
          git checkout -b gh-pages && \
          git push --set-upstream --force origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
